//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 酒店活动
    /// </summary>
    public partial class Activity
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string HotelInfoId { get; set; }
    	/// <summary>
        /// 活动标题
        /// </summary>
    	[DisplayName( "活动标题" )]
        public string Title { get; set; }
    	/// <summary>
        /// 活动描述
        /// </summary>
    	[DisplayName( "活动描述" )]
        public string Describe { get; set; }
    	/// <summary>
        /// 配图
        /// </summary>
    	[DisplayName( "配图" )]
        public string Images { get; set; }
    	/// <summary>
        /// 活动开始时间
        /// </summary>
    	[DisplayName( "活动开始时间" )]
        public System.DateTime StartTime { get; set; }
    	/// <summary>
        /// 活动结束时间
        /// </summary>
    	[DisplayName( "活动结束时间" )]
        public Nullable<System.DateTime> EndTime { get; set; }
    	/// <summary>
        /// 活动地点
        /// </summary>
    	[DisplayName( "活动地点" )]
        public string Place { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public Nullable<System.DateTime> CreateTime { get; set; }
    	/// <summary>
        /// 是否有效
        /// </summary>
    	[DisplayName( "是否有效" )]
        public bool Valid { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
    }
}
