//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 会议室
    /// </summary>
    public partial class Conference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conference()
        {
            this.ConferenceRoom = new HashSet<ConferenceRoom>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 会议室数量
        /// </summary>
    	[DisplayName( "会议室数量" )]
        public int RoomCount { get; set; }
    	/// <summary>
        /// 最大面积
        /// </summary>
    	[DisplayName( "最大面积" )]
        public string MaxArea { get; set; }
    	/// <summary>
        /// 开业年份
        /// </summary>
    	[DisplayName( "开业年份" )]
        public string OpenYear { get; set; }
    	/// <summary>
        /// 最新装修年份
        /// </summary>
    	[DisplayName( "最新装修年份" )]
        public string NewestRenovation { get; set; }
    	/// <summary>
        /// 客房数量
        /// </summary>
    	[DisplayName( "客房数量" )]
        public int GuestRoom { get; set; }
    	/// <summary>
        /// 茶歇价格
        /// </summary>
    	[DisplayName( "茶歇价格" )]
        public string TeaBreak { get; set; }
    	/// <summary>
        /// 自主餐价格
        /// </summary>
    	[DisplayName( "自主餐价格" )]
        public string Buffet { get; set; }
    	/// <summary>
        /// 宴会价格
        /// </summary>
    	[DisplayName( "宴会价格" )]
        public string Banquet { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceRoom> ConferenceRoom { get; set; }
    }
}
