//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// FeatureHotel
    /// </summary>
    public partial class FeatureHotel
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 标题
        /// </summary>
    	[DisplayName( "标题" )]
        public string Title { get; set; }
    	/// <summary>
        /// 说明
        /// </summary>
    	[DisplayName( "说明" )]
        public string Summary { get; set; }
    	/// <summary>
        /// 图片
        /// </summary>
    	[DisplayName( "图片" )]
        public string ImgUrl { get; set; }
    	/// <summary>
        /// 是否有效
        /// </summary>
    	[DisplayName( "是否有效" )]
        public bool Valid { get; set; }
    	/// <summary>
        /// 排序
        /// </summary>
    	[DisplayName( "排序" )]
        public short Sort { get; set; }
    	/// <summary>
        /// 酒店
        /// </summary>
    	[DisplayName( "酒店" )]
        public string HotelInfoId { get; set; }
    	/// <summary>
        /// 特色
        /// </summary>
    	[DisplayName( "特色" )]
        public string FeatureId { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
        public virtual Feature Feature { get; set; }
    }
}
