//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// GuestInvoice
    /// </summary>
    public partial class GuestInvoice
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 公司
        /// </summary>
    	[DisplayName( "公司" )]
        public string Company { get; set; }
    	/// <summary>
        /// 公司地址
        /// </summary>
    	[DisplayName( "公司地址" )]
        public string Address { get; set; }
    	/// <summary>
        /// 公司电话
        /// </summary>
    	[DisplayName( "公司电话" )]
        public string Tel { get; set; }
    	/// <summary>
        /// 开户银行
        /// </summary>
    	[DisplayName( "开户银行" )]
        public string Bank { get; set; }
    	/// <summary>
        /// 开户银行账户
        /// </summary>
    	[DisplayName( "开户银行账户" )]
        public string BankAccount { get; set; }
    	/// <summary>
        /// 纳税人识别号
        /// </summary>
    	[DisplayName( "纳税人识别号" )]
        public string TaxpayerNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string GuestUserId { get; set; }
    
        public virtual GuestUser GuestUser { get; set; }
    }
}
