//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 到达指引
    /// </summary>
    public partial class Guide
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string HotelInfoId { get; set; }
    	/// <summary>
        /// 指引类型
        /// </summary>
    	[DisplayName( "指引类型" )]
        public int Type { get; set; }
    	/// <summary>
        /// 指引名称
        /// </summary>
    	[DisplayName( "指引名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 描述
        /// </summary>
    	[DisplayName( "描述" )]
        public string Describe { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
    }
}
