//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// HomeConfig
    /// </summary>
    public partial class HomeConfig
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 标题
        /// </summary>
    	[DisplayName( "标题" )]
        public string Title { get; set; }
    	/// <summary>
        /// 描述
        /// </summary>
    	[DisplayName( "描述" )]
        public string Summary { get; set; }
    	/// <summary>
        /// 图片
        /// </summary>
    	[DisplayName( "图片" )]
        public string ImgUrl { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 修改时间
        /// </summary>
    	[DisplayName( "修改时间" )]
        public System.DateTime UpdateTime { get; set; }
    	/// <summary>
        /// 是否有效
        /// </summary>
    	[DisplayName( "是否有效" )]
        public bool Valid { get; set; }
    }
}
