//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// HotelService
    /// </summary>
    public partial class HotelService
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 入住时间
        /// </summary>
    	[DisplayName( "入住时间" )]
        public string CheckInTime { get; set; }
    	/// <summary>
        /// 离店时间
        /// </summary>
    	[DisplayName( "离店时间" )]
        public string LeaveTime { get; set; }
    	/// <summary>
        /// 携带宠物
        /// </summary>
    	[DisplayName( "携带宠物" )]
        public string Pet { get; set; }
    	/// <summary>
        /// 自助餐价格
        /// </summary>
    	[DisplayName( "自助餐价格" )]
        public string Buffet { get; set; }
    	/// <summary>
        /// 支持信用卡
        /// </summary>
    	[DisplayName( "支持信用卡" )]
        public string CreditCard { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
    }
}
