//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// HotelInfo
    /// </summary>
    public partial class HotelInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelInfo()
        {
            this.HotelImages = new HashSet<HotelImages>();
            this.HotelPolicy = new HashSet<HotelPolicy>();
            this.Guide = new HashSet<Guide>();
            this.Activity = new HashSet<Activity>();
            this.Room = new HashSet<Room>();
            this.HotelUser = new HashSet<HotelUsers>();
            this.FeatureHotel = new HashSet<FeatureHotel>();
            this.Order = new HashSet<Order>();
            this.Collection = new HashSet<Collection>();
            this.Score = new HashSet<Score>();
            this.Settlement = new HashSet<Settlement>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 名称
        /// </summary>
    	[DisplayName( "名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 英文名
        /// </summary>
    	[DisplayName( "英文名" )]
        public string EnglishName { get; set; }
    	/// <summary>
        /// 客户类型
        /// </summary>
    	[DisplayName( "客户类型" )]
        public short Type { get; set; }
    	/// <summary>
        /// 地址
        /// </summary>
    	[DisplayName( "地址" )]
        public string Adress { get; set; }
    	/// <summary>
        /// 电话
        /// </summary>
    	[DisplayName( "电话" )]
        public string Tel { get; set; }
    	/// <summary>
        /// 星级
        /// </summary>
    	[DisplayName( "星级" )]
        public short Star { get; set; }
    	/// <summary>
        /// 联系人
        /// </summary>
    	[DisplayName( "联系人" )]
        public string Contact { get; set; }
    	/// <summary>
        /// 联系人职位
        /// </summary>
    	[DisplayName( "联系人职位" )]
        public string Position { get; set; }
    	/// <summary>
        /// 联系人电话
        /// </summary>
    	[DisplayName( "联系人电话" )]
        public string Phone { get; set; }
    	/// <summary>
        /// 邮件
        /// </summary>
    	[DisplayName( "邮件" )]
        public string Email { get; set; }
    	/// <summary>
        /// 营业执照
        /// </summary>
    	[DisplayName( "营业执照" )]
        public string BusinessLicense { get; set; }
    	/// <summary>
        /// 特许经营许可证
        /// </summary>
    	[DisplayName( "特许经营许可证" )]
        public string Franchise { get; set; }
    	/// <summary>
        /// 身份证
        /// </summary>
    	[DisplayName( "身份证" )]
        public string Card { get; set; }
    	/// <summary>
        /// 申请时间
        /// </summary>
    	[DisplayName( "申请时间" )]
        public System.DateTime Apply { get; set; }
    	/// <summary>
        /// 审核时间
        /// </summary>
    	[DisplayName( "审核时间" )]
        public Nullable<System.DateTime> ExamineTime { get; set; }
    	/// <summary>
        /// 审核人
        /// </summary>
    	[DisplayName( "审核人" )]
        public string ExamineUser { get; set; }
    	/// <summary>
        /// 审核状态
        /// </summary>
    	[DisplayName( "审核状态" )]
        public int ExamineStatus { get; set; }
    	/// <summary>
        /// 区县Id
        /// </summary>
    	[DisplayName( "区县Id" )]
        public long DistrictId { get; set; }
    	/// <summary>
        /// 城市Id
        /// </summary>
    	[DisplayName( "城市Id" )]
        public long CityId { get; set; }
    	/// <summary>
        /// 开业时间
        /// </summary>
    	[DisplayName( "开业时间" )]
        public Nullable<System.DateTime> OpeningTime { get; set; }
    	/// <summary>
        /// 简介
        /// </summary>
    	[DisplayName( "简介" )]
        public string Synopsis { get; set; }
    	/// <summary>
        /// 装修时间
        /// </summary>
    	[DisplayName( "装修时间" )]
        public Nullable<System.DateTime> RenovationTime { get; set; }
    	/// <summary>
        /// 房间数量
        /// </summary>
    	[DisplayName( "房间数量" )]
        public Nullable<short> RoomCount { get; set; }
    	/// <summary>
        /// 域名
        /// </summary>
    	[DisplayName( "域名" )]
        public string DomainName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public Nullable<short> Valid { get; set; }
    
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelImages> HotelImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelPolicy> HotelPolicy { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Guide> Guide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotelUsers> HotelUser { get; set; }
        public virtual HotelService HotelService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureHotel> FeatureHotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Settlement> Settlement { get; set; }
    }
}
