//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// HotelImages
    /// </summary>
    public partial class HotelImages
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 图片名
        /// </summary>
    	[DisplayName( "图片名" )]
        public string Url { get; set; }
    	/// <summary>
        /// 图片描述
        /// </summary>
    	[DisplayName( "图片描述" )]
        public string Summary { get; set; }
    	/// <summary>
        /// 图片类型
        /// </summary>
    	[DisplayName( "图片类型" )]
        public int Type { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string HotelInfoId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public Nullable<int> Sort { get; set; }
    	/// <summary>
        /// 上传时间
        /// </summary>
    	[DisplayName( "上传时间" )]
        public System.DateTime CreateTime { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
    }
}
