//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Invoice
    /// </summary>
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.Order = new HashSet<Order>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 公司名称
        /// </summary>
    	[DisplayName( "公司名称" )]
        public string Company { get; set; }
    	/// <summary>
        /// 公司地址
        /// </summary>
    	[DisplayName( "公司地址" )]
        public string Address { get; set; }
    	/// <summary>
        /// 公司电话
        /// </summary>
    	[DisplayName( "公司电话" )]
        public string Tel { get; set; }
    	/// <summary>
        /// 开户银行
        /// </summary>
    	[DisplayName( "开户银行" )]
        public string Bank { get; set; }
    	/// <summary>
        /// 银行账户
        /// </summary>
    	[DisplayName( "银行账户" )]
        public string BankAccount { get; set; }
    	/// <summary>
        /// 纳税人识别号
        /// </summary>
    	[DisplayName( "纳税人识别号" )]
        public string TaxpayerNumber { get; set; }
    	/// <summary>
        /// 收件人
        /// </summary>
    	[DisplayName( "收件人" )]
        public string Addressee { get; set; }
    	/// <summary>
        /// 收件人手机
        /// </summary>
    	[DisplayName( "收件人手机" )]
        public string Phone { get; set; }
    	/// <summary>
        /// 收件地址
        /// </summary>
    	[DisplayName( "收件地址" )]
        public string ReceivingAddress { get; set; }
    	/// <summary>
        /// 发票金额
        /// </summary>
    	[DisplayName( "发票金额" )]
        public Nullable<double> Amount { get; set; }
    	/// <summary>
        /// 快递
        /// </summary>
    	[DisplayName( "快递" )]
        public string Express { get; set; }
    	/// <summary>
        /// 快递单号
        /// </summary>
    	[DisplayName( "快递单号" )]
        public string ExpressNumber { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public long ProvinceId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public long CityId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public long DistrictId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string GuestUserId { get; set; }
    	/// <summary>
        /// 开票状态
        /// </summary>
    	[DisplayName( "开票状态" )]
        public short Status { get; set; }
    	/// <summary>
        /// 发票类型
        /// </summary>
    	[DisplayName( "发票类型" )]
        public short Type { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 更新时间
        /// </summary>
    	[DisplayName( "更新时间" )]
        public System.DateTime UpdateTime { get; set; }
    
        public virtual Province Province { get; set; }
        public virtual City City { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        public virtual GuestUser GuestUser { get; set; }
    }
}
