//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Message
    /// </summary>
    public partial class Message
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 接收人
        /// </summary>
    	[DisplayName( "接收人" )]
        public string ToUser { get; set; }
    	/// <summary>
        /// 发送人
        /// </summary>
    	[DisplayName( "发送人" )]
        public string FromUser { get; set; }
    	/// <summary>
        /// 消息标题
        /// </summary>
    	[DisplayName( "消息标题" )]
        public string Title { get; set; }
    	/// <summary>
        /// 消息内容
        /// </summary>
    	[DisplayName( "消息内容" )]
        public string Content { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 是否发送完成
        /// </summary>
    	[DisplayName( "是否发送完成" )]
        public bool Send { get; set; }
    	/// <summary>
        /// 是否阅读
        /// </summary>
    	[DisplayName( "是否阅读" )]
        public bool Read { get; set; }
    	/// <summary>
        /// 上级消息
        /// </summary>
    	[DisplayName( "上级消息" )]
        public string ParentMessageId { get; set; }
    	/// <summary>
        /// 发送时间
        /// </summary>
    	[DisplayName( "发送时间" )]
        public System.DateTime SendTime { get; set; }
    	/// <summary>
        /// 阅读时间
        /// </summary>
    	[DisplayName( "阅读时间" )]
        public System.DateTime RendTime { get; set; }
    }
}
