//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Occupant
    /// </summary>
    public partial class Occupant
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 姓名
        /// </summary>
    	[DisplayName( "姓名" )]
        public string Name { get; set; }
    	/// <summary>
        /// 性别
        /// </summary>
    	[DisplayName( "性别" )]
        public Nullable<short> Sex { get; set; }
    	/// <summary>
        /// 手机
        /// </summary>
    	[DisplayName( "手机" )]
        public string Phone { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string OrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
