//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Order
    /// </summary>
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Comment = new HashSet<Comment>();
            this.DaysPrice = new HashSet<DaysPrice>();
            this.Occupant = new HashSet<Occupant>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 订单编号
        /// </summary>
    	[DisplayName( "订单编号" )]
        public string Number { get; set; }
    	/// <summary>
        /// 下单时间
        /// </summary>
    	[DisplayName( "下单时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 订单状态
        /// </summary>
    	[DisplayName( "订单状态" )]
        public string State { get; set; }
    	/// <summary>
        /// 是否有效
        /// </summary>
    	[DisplayName( "是否有效" )]
        public bool IsValid { get; set; }
    	/// <summary>
        /// 订单来源
        /// </summary>
    	[DisplayName( "订单来源" )]
        public string Source { get; set; }
    	/// <summary>
        /// 订单联系人
        /// </summary>
    	[DisplayName( "订单联系人" )]
        public string ApplyUser { get; set; }
    	/// <summary>
        /// 联系人手机
        /// </summary>
    	[DisplayName( "联系人手机" )]
        public string ApplyPhone { get; set; }
    	/// <summary>
        /// 联系人邮箱
        /// </summary>
    	[DisplayName( "联系人邮箱" )]
        public string ApplyEmail { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 是否支付
        /// </summary>
    	[DisplayName( "是否支付" )]
        public bool Payment { get; set; }
    	/// <summary>
        /// 总金额
        /// </summary>
    	[DisplayName( "总金额" )]
        public double Total { get; set; }
    	/// <summary>
        /// 床型
        /// </summary>
    	[DisplayName( "床型" )]
        public string BedType { get; set; }
    	/// <summary>
        /// 早餐
        /// </summary>
    	[DisplayName( "早餐" )]
        public string Breakfast { get; set; }
    	/// <summary>
        /// 宽带
        /// </summary>
    	[DisplayName( "宽带" )]
        public string Broadband { get; set; }
    	/// <summary>
        /// 价格名称
        /// </summary>
    	[DisplayName( "价格名称" )]
        public string PriceName { get; set; }
    	/// <summary>
        /// 入住时间
        /// </summary>
    	[DisplayName( "入住时间" )]
        public System.DateTime StartTime { get; set; }
    	/// <summary>
        /// 退房时间
        /// </summary>
    	[DisplayName( "退房时间" )]
        public System.DateTime EndTime { get; set; }
    	/// <summary>
        /// 客房数量
        /// </summary>
    	[DisplayName( "客房数量" )]
        public int RoomCount { get; set; }
    	/// <summary>
        /// 日均价
        /// </summary>
    	[DisplayName( "日均价" )]
        public double AvgPrice { get; set; }
    	/// <summary>
        /// 房型名称
        /// </summary>
    	[DisplayName( "房型名称" )]
        public string RoomName { get; set; }
    	/// <summary>
        /// 酒店名称
        /// </summary>
    	[DisplayName( "酒店名称" )]
        public string HotelName { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string GuestUserId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string HotelInfoId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string PriceTypeId { get; set; }
    	/// <summary>
        /// 支付方式
        /// </summary>
    	[DisplayName( "支付方式" )]
        public short PaymentMethod { get; set; }
    	/// <summary>
        /// 是否要发票
        /// </summary>
    	[DisplayName( "是否要发票" )]
        public short IsInvoice { get; set; }
    	/// <summary>
        /// 房价
        /// </summary>
    	[DisplayName( "房价" )]
        public double HousingPrice { get; set; }
    	/// <summary>
        /// 更新人
        /// </summary>
    	[DisplayName( "更新人" )]
        public string UpdateUser { get; set; }
    	/// <summary>
        /// 更新时间
        /// </summary>
    	[DisplayName( "更新时间" )]
        public Nullable<System.DateTime> UpdateTime { get; set; }
    	/// <summary>
        /// 取消备注
        /// </summary>
    	[DisplayName( "取消备注" )]
        public string CancelRemarks { get; set; }
    	/// <summary>
        /// 支付时间
        /// </summary>
    	[DisplayName( "支付时间" )]
        public Nullable<System.DateTime> PayTime { get; set; }
    	/// <summary>
        /// 发票ID
        /// </summary>
    	[DisplayName( "发票ID" )]
        public string InvoiceId { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string SettlementId { get; set; }
    
        public virtual GuestUser GuestUser { get; set; }
        public virtual HotelInfo HotelInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual PriceType PriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaysPrice> DaysPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Occupant> Occupant { get; set; }
        public virtual transaction transaction { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Settlement Settlement { get; set; }
    }
}
