//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// PriceType
    /// </summary>
    public partial class PriceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceType()
        {
            this.Price = new HashSet<Price>();
            this.Order = new HashSet<Order>();
            this.DaysPrice = new HashSet<DaysPrice>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 价格名称
        /// </summary>
    	[DisplayName( "价格名称" )]
        public string Name { get; set; }
    	/// <summary>
        /// 早餐
        /// </summary>
    	[DisplayName( "早餐" )]
        public string Breakfast { get; set; }
    	/// <summary>
        /// 宽带
        /// </summary>
    	[DisplayName( "宽带" )]
        public string Broadband { get; set; }
    	/// <summary>
        /// 支付方式
        /// </summary>
    	[DisplayName( "支付方式" )]
        public short PaymentMethod { get; set; }
    	/// <summary>
        /// 数量
        /// </summary>
    	[DisplayName( "数量" )]
        public string Number { get; set; }
    	/// <summary>
        /// 备注
        /// </summary>
    	[DisplayName( "备注" )]
        public string Remarks { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 更新时间
        /// </summary>
    	[DisplayName( "更新时间" )]
        public System.DateTime UpdateTime { get; set; }
    	/// <summary>
        /// 创建人
        /// </summary>
    	[DisplayName( "创建人" )]
        public string CreateUser { get; set; }
    	/// <summary>
        /// 修改人
        /// </summary>
    	[DisplayName( "修改人" )]
        public string UpdateUser { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string RoomId { get; set; }
    	/// <summary>
        /// 加床价
        /// </summary>
    	[DisplayName( "加床价" )]
        public string ExtraBedPrice { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaysPrice> DaysPrice { get; set; }
    }
}
