//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// 餐饮美食
    /// </summary>
    public partial class Restaurant
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 描述
        /// </summary>
    	[DisplayName( "描述" )]
        public string Describe { get; set; }
    	/// <summary>
        /// 早餐时间
        /// </summary>
    	[DisplayName( "早餐时间" )]
        public string BreakfastTime { get; set; }
    	/// <summary>
        /// 午餐时间
        /// </summary>
    	[DisplayName( "午餐时间" )]
        public string LunchTime { get; set; }
    	/// <summary>
        /// 晚餐时间
        /// </summary>
    	[DisplayName( "晚餐时间" )]
        public string DinnerTime { get; set; }
    	/// <summary>
        /// 席位
        /// </summary>
    	[DisplayName( "席位" )]
        public string Seat { get; set; }
    	/// <summary>
        /// 着装要求
        /// </summary>
    	[DisplayName( "着装要求" )]
        public string Clothing { get; set; }
    	/// <summary>
        /// 地点
        /// </summary>
    	[DisplayName( "地点" )]
        public string Place { get; set; }
    	/// <summary>
        /// 预定方式
        /// </summary>
    	[DisplayName( "预定方式" )]
        public string Reserve { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Image1 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Image2 { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Image3 { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
    }
}
