//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Room
    /// </summary>
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomImages = new HashSet<RoomImages>();
            this.PriceType = new HashSet<PriceType>();
            this.Stock = new HashSet<Stock>();
        }
    
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string HotelInfoId { get; set; }
    	/// <summary>
        /// 房型名
        /// </summary>
    	[DisplayName( "房型名" )]
        public string Name { get; set; }
    	/// <summary>
        /// 英文名
        /// </summary>
    	[DisplayName( "英文名" )]
        public string EnglishName { get; set; }
    	/// <summary>
        /// 面积
        /// </summary>
    	[DisplayName( "面积" )]
        public string Area { get; set; }
    	/// <summary>
        /// 层高
        /// </summary>
    	[DisplayName( "层高" )]
        public string Storey { get; set; }
    	/// <summary>
        /// 床型
        /// </summary>
    	[DisplayName( "床型" )]
        public string BedType { get; set; }
    	/// <summary>
        /// 床型描述
        /// </summary>
    	[DisplayName( "床型描述" )]
        public string BedDescribe { get; set; }
    	/// <summary>
        /// 入住人数
        /// </summary>
    	[DisplayName( "入住人数" )]
        public short OccupancyNumber { get; set; }
    	/// <summary>
        /// 风景
        /// </summary>
    	[DisplayName( "风景" )]
        public string Scenery { get; set; }
    	/// <summary>
        /// 加床
        /// </summary>
    	[DisplayName( "加床" )]
        public string AddBed { get; set; }
    	/// <summary>
        /// 房型数量
        /// </summary>
    	[DisplayName( "房型数量" )]
        public short Number { get; set; }
    	/// <summary>
        /// 无烟房
        /// </summary>
    	[DisplayName( "无烟房" )]
        public string Smokeless { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public System.DateTime CreateTime { get; set; }
    	/// <summary>
        /// 修改时间
        /// </summary>
    	[DisplayName( "修改时间" )]
        public System.DateTime UpdateTime { get; set; }
    	/// <summary>
        /// 淋浴
        /// </summary>
    	[DisplayName( "淋浴" )]
        public bool Shower { get; set; }
    	/// <summary>
        /// 浴缸
        /// </summary>
    	[DisplayName( "浴缸" )]
        public bool Bathtub { get; set; }
    	/// <summary>
        /// 温泉
        /// </summary>
    	[DisplayName( "温泉" )]
        public bool HotSpring { get; set; }
    	/// <summary>
        /// 圆形浴缸
        /// </summary>
    	[DisplayName( "圆形浴缸" )]
        public bool RoundBathtub { get; set; }
    	/// <summary>
        /// 邻窗浴缸
        /// </summary>
    	[DisplayName( "邻窗浴缸" )]
        public bool WindowBathtub { get; set; }
    
        public virtual HotelInfo HotelInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomImages> RoomImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceType> PriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stock { get; set; }
    }
}
