//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// transaction
    /// </summary>
    public partial class transaction
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string id { get; set; }
    	/// <summary>
        /// 交易数据
        /// </summary>
    	[DisplayName( "交易数据" )]
        public string data { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
