//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// Users
    /// </summary>
    public partial class Users
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 用户名
        /// </summary>
    	[DisplayName( "用户名" )]
        public string Name { get; set; }
    	/// <summary>
        /// 密码
        /// </summary>
    	[DisplayName( "密码" )]
        public string Password { get; set; }
    	/// <summary>
        /// 账号类型
        /// </summary>
    	[DisplayName( "账号类型" )]
        public string Role { get; set; }
    	/// <summary>
        /// 创建时间
        /// </summary>
    	[DisplayName( "创建时间" )]
        public Nullable<System.DateTime> RegisterTime { get; set; }
    	/// <summary>
        /// 创建IP
        /// </summary>
    	[DisplayName( "创建IP" )]
        public string RegisterIP { get; set; }
    	/// <summary>
        /// 父级ID
        /// </summary>
    	[DisplayName( "父级ID" )]
        public string ParentId { get; set; }
    	/// <summary>
        /// 是否有效
        /// </summary>
    	[DisplayName( "是否有效" )]
        public bool Vail { get; set; }
    	/// <summary>
        /// 账号说明
        /// </summary>
    	[DisplayName( "账号说明" )]
        public string Summary { get; set; }
    	/// <summary>
        /// 账号状态
        /// </summary>
    	[DisplayName( "账号状态" )]
        public short Status { get; set; }
    }
}
