//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    /// <summary>
    /// UserLog
    /// </summary>
    public partial class UserLog
    {
    	/// <summary>
        /// 
        /// </summary>
    	[DisplayName( "" )]
        public string Id { get; set; }
    	/// <summary>
        /// 日志等级
        /// </summary>
    	[DisplayName( "日志等级" )]
        public string Level { get; set; }
    	/// <summary>
        /// 日志类型
        /// </summary>
    	[DisplayName( "日志类型" )]
        public string TypeName { get; set; }
    	/// <summary>
        /// 日志内容
        /// </summary>
    	[DisplayName( "日志内容" )]
        public string Content { get; set; }
    	/// <summary>
        /// 用户id
        /// </summary>
    	[DisplayName( "用户id" )]
        public string UserId { get; set; }
    	/// <summary>
        /// 用户类型
        /// </summary>
    	[DisplayName( "用户类型" )]
        public string UserType { get; set; }
    	/// <summary>
        /// 用户名
        /// </summary>
    	[DisplayName( "用户名" )]
        public string UserName { get; set; }
    }
}
